baseurl = "https://scottsapptest.github.io/"
copyright = "&copy; 2016 Your Name"
googleAnalytics = ""
languageCode = "en-us"
theme = "academic"
title = "Academic Theme"
[[menu.main]]
name = "Home"
url = "#top"
weight = 1
[[menu.main]]
name = "Publications"
url = "#publications"
weight = 2
[[menu.main]]
name = "Posts"
url = "#posts"
weight = 3
[[menu.main]]
name = "Projects"
url = "#projects"
weight = 4
[[menu.main]]
name = "Teaching"
url = "#teaching"
weight = 5
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6
[params]
address = "Stanford AI Lab, Stanford University, California, 90210, USA."
avatar = "portrait.jpg"
custom_css = []
custom_js = []
date_format = "Mon, Jan 2, 2006"
email = "test@example.org"
keybase = ""
math = false
name = "Lena Smith"
organization = "Stanford University"
phone = "888 888 88 88"
role = "Professor of Artificial Intelligence"
sharing = true
[[params.social]]
icon = "envelope"
icon_pack = "fa"
link = "mailto:test@example.org"
[[params.social]]
icon = "twitter"
icon_pack = "fa"
link = "//twitter.com/GeorgeCushen"
[[params.social]]
icon = "google-scholar"
icon_pack = "ai"
link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"
[[params.social]]
icon = "github"
icon_pack = "fa"
link = "//github.com/gcushen"
